//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "dynamic")]
pub struct Model {
    /// 动态 id（id_str）
    #[sea_orm(primary_key)]
    pub id: String,
    pub source_id: i32,
    /// 动态类型，如 DYNAMIC_TYPE_AV / DYNAMIC_TYPE_DRAW / DYNAMIC_TYPE_COMMON_SQUARE / DYNAMIC_TYPE_FORWARD
    pub dyn_type: String,
    /// 渲染后的正文文本
    pub content: String,
    /// 图片 URL 列表
    pub pics: Option<Json>,
    /// 点赞/评论/转发数（module_stat）
    pub stat: Option<Json>,
    pub pub_ts: DateTime,
    /// 评论类型（basic.comment_type），用于评论接口
    pub comment_type: i64,
    /// 评论对象 id（basic.rid_str），用于评论接口
    pub comment_oid: String,
    /// 发布 IP 属地（如"江苏"），可为空
    pub location: String,
    /// 原始接口 JSON
    pub raw: Option<String>,
    pub download_status: u32,
    pub path: String,
    pub valid: bool,
    /// 手动标记重新同步评论
    pub rescan_reply: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dynamic_source::Entity",
        from = "Column::SourceId",
        to = "super::dynamic_source::Column::Id"
    )]
    DynamicSource,
    #[sea_orm(has_many = "super::reply::Entity")]
    Reply,
}

impl Related<super::dynamic_source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicSource.def()
    }
}

impl Related<super::reply::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reply.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
