//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod collection;
pub mod config;
pub mod dynamic;
pub mod dynamic_source;
pub mod elec_rank;
pub mod elec_stat;
pub mod favorite;
pub mod page;
pub mod reply;
pub mod submission;
pub mod upper_stat;
pub mod video;
pub mod video_stat;
pub mod watch_later;
