//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "reply")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rpid: i64,
    /// 所属动态 id
    pub dynamic_id: String,
    /// 楼中楼回复的父评论 rpid，顶级评论为 None
    pub parent_rpid: Option<i64>,
    pub uname: String,
    pub avatar: String,
    pub content: String,
    pub images: Option<Json>,
    pub ctime: DateTime,
    pub raw: Option<String>,
    pub download_status: u32,
    pub valid: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dynamic::Entity",
        from = "Column::DynamicId",
        to = "super::dynamic::Column::Id"
    )]
    Dynamic,
}

impl Related<super::dynamic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dynamic.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
