//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]
#[sea_orm(table_name = "upper_stat")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// UP 主 id
    pub upper_id: i64,
    pub name: String,
    pub sign: String,
    pub face: String,
    pub fan_count: i64,
    pub follow_count: i64,
    pub video_count: i64,
    /// 动态中的视频数量（已同步的 DYNAMIC_TYPE_AV 动态数）
    pub dynamic_video_count: i64,
    pub view_count: i64,
    pub like_count: i64,
    pub recorded_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
