name: Build Main Binary And Release

on:
  push:
    tags:
      - v*

jobs:
  build-binary:
    uses: nothingness0db/bili-sync/.github/workflows/build-binary.yaml@main
  github-release:
    name: Create GitHub Release
    needs: build-binary
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download release artifact
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: bili-sync-rs*
          tag_name: ${{ github.ref_name }}
          draft: true
